name: Build and Check

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    name: Astro Check for Node.js
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup aube
        uses: endevco/aube-action@f82ca2f6c943dbde1904945d9f0ee1a0faf8e945 # v1.0.0
        with:
          version: 1.9.1
          node-version: auto

      - name: Install dependencies
        run: aube ci

      - name: Run Astro Check
        run: aube run astro check

      - name: Type Check
        run: aube type-check

      - name: format and lint
        run: |
          aube fmt:check
          aube lint

  build:
    runs-on: ubuntu-latest
    name: Astro Build for Node.js
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup aube
        uses: endevco/aube-action@f82ca2f6c943dbde1904945d9f0ee1a0faf8e945 # v1.0.0
        with:
          version: 1.9.1
          node-version: auto

      - name: Install dependencies
        run: aube ci

      - name: Run Astro Build
        run: aube run astro build
